<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE cv[
<!ELEMENT cv (presentacion, (datos_academicos | experiencia_laboral)+, (lectura|deportes|otros)*, referencias*)>
<!ELEMENT presentacion (#PCDATA)>
<!ELEMENT datos_academicos (#PCDATA)>
<!ELEMENT experiencia_laboral (#PCDATA)>
<!ELEMENT lectura (#PCDATA)>
<!ELEMENT deportes (#PCDATA)>
<!ELEMENT otros (#PCDATA)>
<!ELEMENT referencias (#PCDATA)>
]>

<!-- El elemento tiene una presentacion , datos academicos o experiencia laboral al menos una vez, lectura deportes o otros pueden aparecer o no aparecer uno de ellos y 
referencias puede aparecer o no. -->

<cv>
    <presentacion></presentacion>
    <datos_academicos></datos_academicos>
    <deportes></deportes>
    <referencias></referencias>

</cv>