<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resultados [
<!ELEMENT resultados (resultado)*>
<!ELEMENT resultado (local, visitante)>
<!ELEMENT local (#PCDATA|goles)*>
<!ELEMENT visitante (#PCDATA|goles)*>
<!ELEMENT goles (#PCDATA)>
]>
<resultados>
    <resultado>
        <local>Nottingham Presa <goles>0</goles></local>
        <visitante>- Inter de Mitente <goles>1</goles></visitante>
    </resultado>
    <resultado>
        <local>Vodka Juniors<goles>3</goles></local>
        <visitante>Sparta da Risa<goles>2</goles></visitante>
    </resultado>
    <resultado>
        <local>Water de Munich<goles>4</goles></local>
        <visitante>Esteaua es del grifo<goles>2</goles></visitante>
    </resultado>
    
</resultados>