=== ibq-daw1-1920-20/lmsgi/Actividad_04_04/Ejercicio4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<!--Defenimos los elementos simples-->
<xs:element name="base" type ="xs:integer"/>
<xs:element name="altura" type ="xs:string"/>
<xs:element name="radio" type ="xs:string"/>
<xs:element name="nombre" type ="xs:string"/>

<!--Defenimos los atributos-->
<xs:attribute name = "RGB">
  <xs:simpleType>
    <xs:restriction base ="xs:string">
      <xs:pattern value="[A-F0-9]{6}"/>
    </xs:restriction>
  </xs:simpleType>
</xs:attribute>


<!--Definimos los elementos complejos:figura-->
<xs:element name="figura">
    <xs:complexType>

    <xs:sequence>
        <xs:element ref ="nombre"/>
        <xs:element ref ="altura" minOccurs="0"/>
        <xs:element ref ="base" minOccurs="0"/>
        <xs:element ref ="radio" minOccurs="0"/>
    </xs:sequence>

    <xs:attribute ref = "RGB"/>
    </xs:complexType>

</xs:element>

<!--Definimos los elemenots complejos:figuraGeometrica-->

<xs:element name="figuraGeometrica">
    <xs:complexType>

    <xs:sequence>
        <xs:element ref ="figura" maxOccurs="50" />
    </xs:sequence>
    </xs:complexType>

</xs:element>
</xs:schema>

=== ibq-daw1-1920-20/lmsgi/REPOSITORIOS_GITHUB_LMSGI/LMSGI/lmsgi/Actividad_04_04/Ejercicio4.xml
<?xml version="1.0" encoding="UTF-8"?>

<figuraGeometrica xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation = "Ejercicio4.xsd">
    <figura RGB = "FFAA9B">
        <nombre>Cuadrado</nombre>
        <altura>10</altura>
        <base>5</base>
    </figura>
    <figura RGB = "AAAA00">
        <nombre>tringulo</nombre>
        <altura>8</altura>
        <base>2</base>
    </figura>
    <figura RGB = "AA21F2">
        <nombre>circulo</nombre>
        <radio>10</radio>
    </figura>
</figuraGeometrica>
