=== ibq-daw1-1920-20/lmsgi/Actividad_04_04/Ejercicio3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">


<!--Defenimos los elementos simples-->
<xs:element name="nombre" type ="xs:string"/>
<xs:element name="apellidos" type ="xs:string"/>
<xs:element name="nota">
<xs:simpleType>
  <xs:union>
    <xs:simpleType>
      <xs:restriction base ="xs:decimal">
      <xs:maxInclusive value="10"/>
      <xs:minInclusive value="0"/>
      <xs:fractionDigits value="2"/>
    </xs:restriction>
  </xs:simpleType> 
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="No presentado"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:union>
</xs:simpleType>
</xs:element>  
<xs:element name="edad">
  <xs:simpleType>
    <xs:restriction base ="xs:integer">
      <xs:minInclusive value="15"/>
      <xs:maxInclusive value="75"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element>
<xs:element name="comentario" type = "xs:string"/>
<xs:element name="calle">
  <xs:simpleType>
    <xs:restriction base ="xs:string">
      <xs:maxLength value="18"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element>  
<xs:element name="numero" type = "xs:positiveInteger"/>
<xs:element name="ciudad" type = "xs:string"/>
<xs:element name="codigoPostal">
  <xs:simpleType>
    <xs:restriction base ="xs:integer">
      <xs:totalDigits value ="5"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element>  






<!-- Definimos los atributos-->
<xs:attribute name = "DNI">
  <xs:simpleType>
    <xs:restriction base ="xs:string">
      <xs:pattern value="\d{7,8}[A-Z]"/>
    </xs:restriction>
  </xs:simpleType>
</xs:attribute>

<!-- Definimos los elementos complejos:alumno -->
<xs:element name="alumno">

 <xs:complexType>

  <xs:sequence>
    <xs:element ref="nombre"/>
    <xs:element ref="apellidos"/>
    <xs:element ref="nota"/>
    <xs:element ref="edad" minOccurs="0"/>
    <xs:element ref="comentario"/>
    <xs:element ref="calle" minOccurs="0"/>
    <xs:element ref="numero" minOccurs="0"/>
    <xs:element ref="ciudad" minOccurs="0"/>
    <xs:element ref="codigoPostal" minOccurs="0"/>
  </xs:sequence>

  <xs:attribute ref= "DNI" />

 </xs:complexType>

</xs:element> 

<!-- Definimos los elementos complejos:clase-->
<xs:element name="clase">
    <xs:complexType>

    <xs:sequence>
        <xs:element ref ="alumno" maxOccurs="30" />
    </xs:sequence>
    </xs:complexType>

</xs:element>

</xs:schema>

=== ibq-daw1-1920-20/lmsgi/REPOSITORIOS_GITHUB_LMSGI/LMSGI/lmsgi/Actividad_04_04/Ejercicio3.xml
<?xml version="1.0" encoding="UTF-8"?>

<clase xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation = "Ejercicio3.xsd">

<alumno DNI = "99887766X">

    <nombre>Dario</nombre>
    <apellidos>Fernández Álvarez</apellidos>
    <nota>3.50</nota>
    <edad>45</edad>
    <comentario>Necesita mejorar</comentario>
    <calle>Galiana</calle>
    <numero>23</numero>
    <ciudad>Áviles</ciudad>
    <codigoPostal>33400</codigoPostal>

</alumno>

<alumno DNI = "0132233A">
    <nombre>Luis</nombre>
    <apellidos>Álvarez garcía</apellidos>
    <nota>6.75</nota>
    <edad>75</edad>
    <comentario>Copió de Dario, Alfredo y Pilar</comentario>

</alumno>

<alumno DNI = "5556677Z">
    <nombre>Pilar</nombre>
    <apellidos>Rodríguez Menéndez</apellidos>
    <nota>8.25</nota>
    <comentario>Copió de todos</comentario>    

</alumno>

<alumno DNI = "66554433T">
    <nombre>Alfredo</nombre>
    <apellidos>Martínez González</apellidos>
    <nota>No presentado</nota>
    <edad>42</edad>
    <comentario>Estudió en Universidad de Oviedo</comentario>
    <calle>Comandante Valle</calle>
    <numero>5</numero>
    <ciudad>Oviedo</ciudad>
    <codigoPostal>33021</codigoPostal>


</alumno>




</clase>
